### ISSUE TITLE
Guia para indipendizarse de netfly

### ISSUE THREAD

**Issue by luipir** [montera34/qgis-es#28]
Hola

puedes indicar los pasos para compilar y despliegar todo sin necesidad de usar el servicio online de netfly? vale tambien usar netfly instalado localmente, pero sirve una guia o una docker todo preparado para activar toda la compilacion de hugo.

no se si me he esplicado bien... es necesario se indipendiente de servicios online que mañana (con bstante seguridad) desapareceran.

un saludo

**Comment by ccamara** [comment]
Para tu tranquilidad, el uso de netlify es opcional y podría cerrar mañana (al igual que github) sin que se perdiera ninguna información, aunque habría que hacer adaptaciones (del mismo modo que si cerrase github tendríamos que cambiar el repositorio remoto pero no perderíamos apenas nada -nada de contenido-). En realidad, hugo no tiene nada que ver con netlify. Más bien, netlify ofrece servicios y productos que pueden utilizar hugo, entre otras.

Tal y como acordamos, la web es una web estática. Como se trata de una web sin servidor y escribimos contenido en markdown implica que "alguien" tiene que convertirlo a html. Ese alguien es hugo. Como no tenemos servidor, el proceso habitual es ejecutar hugo en local (esto es en la máquina de cualquier persona que quiera editar la web) y subir los archivos html al repo. 

Eso implicaría:

1. Instalar hugo en cada máquina de cada persona que quiera editar la web (https://gohugo.io/getting-started/installing/)
2. Ejecutar hugo `hugo serve` o alguno de los comandos que encontrarás en la documentación oficial:  https://gohugo.io/getting-started/usage/
3. Subir el site generado al repositorio
4. Configurar el dominio para que apunte a una carpeta o una rama (según se haya configurado el repo en el paso 3) 


Aunque esto se puede hacer, esto es tedioso y problemático porque exige que todos los editores os lo instaléis.

La forma de evitarlo es implementar un sistema de integración contínua que ejecute hugo en cada commit y haga el deploy en el lugar especificado. Hay muchas maneras de poder hacer esto (gitlab ci, quizá con travis, jenkins...) pero está fuera del alcance cubrir dichas soluciones.

En lugar de ello, he optado por utilizar el servicio que ofrece netlify a través de su programa para proyectos opensource (https://www.netlify.com/legal/open-source-policy/#open-source-plan-policy) que equivale al plan profesional (https://www.netlify.com/pricing/)

Esto tiene varias ventajas:

1. No es necesario que nadie se instale nada en su ordenador (aunque puede instalarse hugo para trabajar en local si se desea)
2. Cada deploy ejecuta una build para que hugo renderice el site. Si la build es exitosa, sube los cambios y los muestra en el dominio.
3. Pueden configurarse "entornos de desarrollo": Pueden hacerse previews de commits en ramas distintas para hacer pruebas sin afectar el site en producción
4. Gestión automática de certificado https://

Como decía, esta parte final es opcional, pero facilita muchísimo la colaboración y la gestión del site. En caso de querer prescindir de los servicios de Netlify puede hacerse, pero exige o bien utilizar otros servicios o bien instalar software en un servidor al que no tenemos acceso. Sea como fuere, está fuera del alcance del proyecto.

**Comment by luipir** [comment]
esto me queda claro que esta hecho por simplificar... pero creo que se necesita uan guia para compilar la pagina statica sin usar el servicio web. 
Yo tengo Hugo configurado por la pagina de QCooperative, es verdad que es necesario haerlo manual, pero es necesario tener la procedura documentada por si a caso pasa algo a netfly.
Algo cop detalles de los pasos, mas o meno como para la pagina de qcoop (https://github.com/qcooperative/website/blob/master/README.md)

Para mi punto de vista, es necesario tener instrucciones para un plan de contingencia... si todo sigue bien, nos olvidamos de como funciona netfly y el dia que desaparece (y antes o despues va a pasar) no encontramos nadie que se acuerde como compilar la pagina estatica.

**Comment by luipir** [comment]
perfect, tnx

**Comment by ccamara** [comment]
A tí por ponerlo fácil. No entendí exactamente qué querías la primera vez.
